version: 0.2

env:
  variables:
    DOCKER_IMAGE_NAME: "simple-python-flask-appone"
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies......"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests......"
      - echo "Building Docker image...."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - echo "Cleaning environment variables...."
      - DOCKER_REGISTRY_URL=$(echo "$DOCKER_REGISTRY_URL" | tr -d '\n\r')
      - DOCKER_REGISTRY_USERNAME=$(echo "$DOCKER_REGISTRY_USERNAME" | tr -d '\n\r')
      - echo "DOCKER_REGISTRY_URL='$DOCKER_REGISTRY_URL'"
      - echo "DOCKER_REGISTRY_USERNAME='$DOCKER_REGISTRY_USERNAME'"
     
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$DOCKER_IMAGE_NAME:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$DOCKER_IMAGE_NAME:latest"
  post_build:
    commands:
      - echo "Build completed successfully!"
      
artifacts:
  files:
    - "**/*"
  base-directory: ../simple-python-app
